# spring配置
spring:
  # 数据源配置
  datasource:
#    url: jdbc:mysql://47.94.213.240:3306/spikeDemo?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
#    username: carl
#    password: 1q2w3e4r
    url: jdbc:mysql://localhost:3306/spikeDemo?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    username: root
    password: ROOT
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    tomcat:
      max-active: 1000
      initial-size: 500
      max-wait: 60000
      min-idle: 500
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
    dbcp2:
      pool-prepared-statements: true
      max-open-prepared-statements: 20
  # thymeleaf配置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    servlet:
      content-type: text/html
    encoding: UTF-8
    mode: HTML5
    enabled: true
  #static
  resources:
    add-mappings: true
    cache:
      period: 3600
    chain:
      cache: true
      enabled: true
      html-application-cache: true
    static-locations: classpath:/static/

# mybatis配置
mybatis:
  # 对应的实体类的位置
  type-aliases-package: com.hui.miaosha.domain
  configuration:
    # 开启自动驼峰命名
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 3000
  # mapper对应的xml
  mapper-locations: classpath:com/hui/miaosha/dao/*.xml

# redis配置
redis:
  host: 47.94.213.240
  port: 6379
  timeout: 3
  password: 123456
  poolMaxTotal: 1000
  poolMaxIdle: 1000
  poolMaxWait: 300
